---
env:
  browser: true
  es6: true
  node: true
plugins:
  - import
extends:
  - ./base/errors.yml
  - ./base/best-practices.yml
  - ./base/strict.yml
  - ./base/variables.yml
  - ./base/node.yml
  - ./base/style.yml
  - ./base/es6.yml
  - ./base/imports.yml
